### ISSUE TITLE
Overwritten methods

### ISSUE THREAD

**Issue by jfb-h** [JuliaPatents/PatentsLens.jl#3]
There seem to be some methods from PatentsBase that are overwritten in PatentsLens. 
See the following warning when both are used in a package:

```
[ Info: Precompiling Data [717f8fcf-ef02-410e-a483-944bf3c10701]
WARNING: Method definition citationgraph(Array{var"#s10", 1} where var"#s10"<:PatentsBase.AbstractFamily) in module PatentsBase at /home/jakob/.julia/packages/PatentsBase/qrnVS/src/citations.jl:156 overwritten in module PatentsLens at /home/jakob/.julia/packages/PatentsLens/pfvqF/src/model/citations.jl:62.
  ** incremental compilation may be fatally broken for this module **
```

**Comment by Seitzal** [comment]
I moved the implementation of citationgraph() from PatentsLens to PatentsBase a while ago, but apparently only published a new version of PatentsBase, not PatentsLens, to the registry afterwards, causing a fresh install of both packages to contain the implementation code twice. This should now be fixed and should no longer occur after updating project dependencies.
